// Generated by gencpp from file first_pkg/V2V.msg
// DO NOT EDIT!


#ifndef FIRST_PKG_MESSAGE_V2V_H
#define FIRST_PKG_MESSAGE_V2V_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Twist.h>

namespace first_pkg
{
template <class ContainerAllocator>
struct V2V_
{
  typedef V2V_<ContainerAllocator> Type;

  V2V_()
    : id(0)
    , name()
    , battery_level(0.0)
    , car_pose()
    , car_speed()  {
    }
  V2V_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , battery_level(0.0)
    , car_pose(_alloc)
    , car_speed(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef float _battery_level_type;
  _battery_level_type battery_level;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _car_pose_type;
  _car_pose_type car_pose;

   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _car_speed_type;
  _car_speed_type car_speed;





  typedef boost::shared_ptr< ::first_pkg::V2V_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_pkg::V2V_<ContainerAllocator> const> ConstPtr;

}; // struct V2V_

typedef ::first_pkg::V2V_<std::allocator<void> > V2V;

typedef boost::shared_ptr< ::first_pkg::V2V > V2VPtr;
typedef boost::shared_ptr< ::first_pkg::V2V const> V2VConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_pkg::V2V_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_pkg::V2V_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first_pkg::V2V_<ContainerAllocator1> & lhs, const ::first_pkg::V2V_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.battery_level == rhs.battery_level &&
    lhs.car_pose == rhs.car_pose &&
    lhs.car_speed == rhs.car_speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first_pkg::V2V_<ContainerAllocator1> & lhs, const ::first_pkg::V2V_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_pkg::V2V_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_pkg::V2V_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_pkg::V2V_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_pkg::V2V_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pkg::V2V_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_pkg::V2V_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_pkg::V2V_<ContainerAllocator> >
{
  static const char* value()
  {
    return "718b3de2696f00d3e8710323efe57f63";
  }

  static const char* value(const ::first_pkg::V2V_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x718b3de2696f00d3ULL;
  static const uint64_t static_value2 = 0xe8710323efe57f63ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_pkg::V2V_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_pkg/V2V";
  }

  static const char* value(const ::first_pkg::V2V_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_pkg::V2V_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n"
"string name\n"
"float32 battery_level\n"
"geometry_msgs/Pose2D car_pose\n"
"geometry_msgs/Twist car_speed\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::first_pkg::V2V_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_pkg::V2V_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.battery_level);
      stream.next(m.car_pose);
      stream.next(m.car_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct V2V_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_pkg::V2V_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_pkg::V2V_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "battery_level: ";
    Printer<float>::stream(s, indent + "  ", v.battery_level);
    s << indent << "car_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.car_pose);
    s << indent << "car_speed: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.car_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_PKG_MESSAGE_V2V_H
