// Generated by gencpp from file my_first_service/addTwoInt.msg
// DO NOT EDIT!


#ifndef MY_FIRST_SERVICE_MESSAGE_ADDTWOINT_H
#define MY_FIRST_SERVICE_MESSAGE_ADDTWOINT_H

#include <ros/service_traits.h>


#include <my_first_service/addTwoIntRequest.h>
#include <my_first_service/addTwoIntResponse.h>


namespace my_first_service
{

struct addTwoInt
{

typedef addTwoIntRequest Request;
typedef addTwoIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addTwoInt
} // namespace my_first_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_first_service::addTwoInt > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::my_first_service::addTwoInt&) { return value(); }
};

template<>
struct DataType< ::my_first_service::addTwoInt > {
  static const char* value()
  {
    return "my_first_service/addTwoInt";
  }

  static const char* value(const ::my_first_service::addTwoInt&) { return value(); }
};


// service_traits::MD5Sum< ::my_first_service::addTwoIntRequest> should match
// service_traits::MD5Sum< ::my_first_service::addTwoInt >
template<>
struct MD5Sum< ::my_first_service::addTwoIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_service::addTwoInt >::value();
  }
  static const char* value(const ::my_first_service::addTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_service::addTwoIntRequest> should match
// service_traits::DataType< ::my_first_service::addTwoInt >
template<>
struct DataType< ::my_first_service::addTwoIntRequest>
{
  static const char* value()
  {
    return DataType< ::my_first_service::addTwoInt >::value();
  }
  static const char* value(const ::my_first_service::addTwoIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_first_service::addTwoIntResponse> should match
// service_traits::MD5Sum< ::my_first_service::addTwoInt >
template<>
struct MD5Sum< ::my_first_service::addTwoIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_first_service::addTwoInt >::value();
  }
  static const char* value(const ::my_first_service::addTwoIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_first_service::addTwoIntResponse> should match
// service_traits::DataType< ::my_first_service::addTwoInt >
template<>
struct DataType< ::my_first_service::addTwoIntResponse>
{
  static const char* value()
  {
    return DataType< ::my_first_service::addTwoInt >::value();
  }
  static const char* value(const ::my_first_service::addTwoIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_FIRST_SERVICE_MESSAGE_ADDTWOINT_H
